MCU = STM32F401
BOOTLOADER = stm32-dfu
KEYBOARD_SHARED_EP = yes

CONSOLE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
